baseurl: /myBlog # the subpath of your site, e.g. /blog/

# Site settings
title: My first really cool page!
email: rcorbeil@softstackfactory.com
description: > # this means to ignore newlines until "baseurl:"
  Here is an awesome description for my new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: http://rcorbeil-ssl.github.io/ # the base hostname & protocol for your site
twitter_username: noneAtThisTime
github_username:  rcorbeil-ssf

# Build settings
markdown: kramdown